// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlHP7RQo6r3FwdcWKJt6vtXD9mdd0NIrs',
    appId: '1:478810615854:web:3c48d32711336c1db06fbf',
    messagingSenderId: '478810615854',
    projectId: 'bank-mobile-application',
    authDomain: 'bank-mobile-application.firebaseapp.com',
    storageBucket: 'bank-mobile-application.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDVa3L6td1ZfVvG7yFdnmFU5Ba3pASLpA',
    appId: '1:478810615854:android:18ee166d15422bcbb06fbf',
    messagingSenderId: '478810615854',
    projectId: 'bank-mobile-application',
    storageBucket: 'bank-mobile-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkqQO3Z1teNg-3Ok0Y0CN-1_PHi45K5n8',
    appId: '1:478810615854:ios:0f456ec756f9e865b06fbf',
    messagingSenderId: '478810615854',
    projectId: 'bank-mobile-application',
    storageBucket: 'bank-mobile-application.firebasestorage.app',
    iosBundleId: 'com.example.bankMobileAppProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkqQO3Z1teNg-3Ok0Y0CN-1_PHi45K5n8',
    appId: '1:478810615854:ios:0f456ec756f9e865b06fbf',
    messagingSenderId: '478810615854',
    projectId: 'bank-mobile-application',
    storageBucket: 'bank-mobile-application.firebasestorage.app',
    iosBundleId: 'com.example.bankMobileAppProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlHP7RQo6r3FwdcWKJt6vtXD9mdd0NIrs',
    appId: '1:478810615854:web:c5e4d3200db4fe54b06fbf',
    messagingSenderId: '478810615854',
    projectId: 'bank-mobile-application',
    authDomain: 'bank-mobile-application.firebaseapp.com',
    storageBucket: 'bank-mobile-application.firebasestorage.app',
  );
}
